app = "lucien-outside"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.http_checks]]
  path = "/health"
  interval = "10s"
  timeout = "2s"
  grace_period = "25s"
  method = "GET"

  [[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443
