[packages]
python = { version = "3.8" }

[builders.mybuilder.env]
PYTHON_VERSION = "3.8"

[builders.mybuilder.commands]
before-build = "pip install --upgrade pip"
before-build = "pip install -r requirements.txt"
before-deploy = "py_compile main.py"
cmd = "python3 main.py"

[procs]
app = {
  cmd = "python3 main.py",
  ports = [80],
  entrypoints = { http = 80 }
}
