name: Deploy to Fly.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
